README.md, file_paths.md
Consolidate information from various tickets (PUP-3809, PUP-3632,
RE-3976 and confluence).
=> (PUP-4026) Specify puppet install paths

file_paths.md
Update file paths to specify module directory creation
=> (PUP-4067) Windows MSI creates $codedir\modules

file_paths.md
Adds per-user directories for *nix and Windows.
=> (PUP-4189) Specify per-user directories

language/types_values_variables.md
This commit adds a description of the NotUndef type and changes the
description of the Struct type to reflect that the StructMember key
now is a type.
=> (PUP-4483) Add NotUndef to the 'Types, Values, and Variables' page

file_paths.md
* Remove cfacter references as it's not shipped anymore
* Update to indicate facter is now an exe
=> (maint) Update for facter 3

file_paths.md
Add nssm.exe to the Windows/Services directory.
=> (RE-5640) Incorporate NSSM into the MSI package

file_paths.md
Update to the file_path.md file to capture recent pxp-agent changes
=> (PA-24) File Path specifications changes for PXP-Agent

language/puppet-functions.md
This adds language to the puppet-functions.md that clarifies the rules for naming puppet functions and how autoloading and ad-hoc manifest defined functions work.
=> (PUP-5561) Clarify rules for autoloading puppet functions

file_paths.md
Update to the file_path.md file to capture recent additions for PE client tools
=> (PE-12458) File path changes for PE client tools

language/types_values_variables.md
This adds the Iterable and Iterator types to the specification. They are
introduced in Puppet 4.4.0.
=> (PUP-5772) Specify the Iterable and Iterator types.

language/expressions.md, language/types_values_variables.md
This also improves the text for the Unary Splat operator
=> (PUP-5836) Add specificatio of splat iterator to array

language/types_values_variables.md
The `Iterable` type was missing `String` as a possible assignable type.
This commit adds documentation stating the `String` is assignable to `Iterable` and
`Iterable[String]`.
Ignore the whitespace changes; my editor strips trailing whitespace.
=> (maint) Add String as Iterable type.

language/expressions.md, language/lexical_structure.md, language/types_values_variables.md
This adds a specification of the two types SemVer and SemVerRange
=> (PUP-6221) Specify SemVer and SemVerRange types

language/func-api.md
This specifies how 4.x function loading works; what is supported in
terms of creating name spaced functions and the paths from which they
are loaded.
=> (PUP-6056) Specify 4x function API loading

language/expressions.md, language/lexical_structure.md, language/types_values_variables.md
Supersedes [PR-84](/puppetlabs/puppet-specifications/pull/84).
=> (PUP-6688) Add specification of Timestamp and Timespan.

language/expressions.md, language/func-api.md, language/puppet-functions.md
Changes the descriptions involving autoload behavior with respect
to puppet functions and types that are declared in an environment.
=> (PUP-6992) Change autoload description with respect to environment

tasks/README.md, tasks/error.json, tasks/task.json
Adds the version 1 task specification and related schema.
=> (ORCH-2119) Add task specification

tasks/README.md, tasks/task.json
Update specification for multi-file task support.
=> (BOLT-556) Shareable tasks specification

language/resource-api/README.md
Minor update re. commit dd64c97.
=> Minor update to README.md

language/resource-api/README.md
The two new known issues reference one already known issue (commands API), and one new use-case provided by @seanmil .
=> RSAPI: Add user provided requirements

language/resource-api/README.md
Not happy with the transport implementation being described here, I think we need an interface class.
Added file paths to the code samples, as in @DavidS notes. I think they help make things clearer.
=> WIP - (FM-7596) Draft of RSAPI Transport layer
