file_paths.md

The binary is called puppetserver not puppetmaster.

Rename puppetmaster to puppetserver

---

file_paths.md

Previously we only specified the location that puppet pluginsyncs
external facts to. Unfortunately, facter's facts.d directory was not
specified.
This commit adds facter's facts.d directory to
/opt/puppetlabs/facter/facts.d. It is not located in
/opt/puppetlabs/puppet, because this facts.d directory is a facter
implementation detail, and puppet has no knowledge of it.

(PUP-4026) Add facter's facts.d

---

file_paths.md

On unix the mcollective daemon (mcollectived) logs to
/var/log/puppetlabs/mcollective.log and records a pidfile to
/var/run/puppetlabs/mcollectived.pid.  The other named log and
pidfile are not used.

(maint) correct mcollective unix daemon paths

---

file_paths.md

Adds windows paths. All paths are the same prior to AIO except for
`codedir` (new) and `vardir` is renamed from `var` to `cache` for
consistency with *nix.

(PUP-4026) Add Windows paths

---

file_paths.md

Describes what accounts and services are created by the `puppetserver`
and `puppet-agent` packages, and which account each service runs as.

Specify account and service names

---

file_paths.md

In Puppet config, :devicedir maps to .../devices. The specification had devices and devicedir swapped. Fix the spec.

(doc) Swap name and path for devicedir

---

file_paths.md

Without this patch the location of the puppetserver log files and pid files are
ambiguous.  The location inferred by the locations of the agent.pid and
puppet.log are problematic because puppetserver does not run as root and as
such will not be able to create new files in `/var/run/puppetlabs` and
`/var/log/puppetlabs`.
This pull request proposes puppetserver writable directories of
`/var/log/puppetlabs/puppetserver/` and `/var/run/puppetlabs/puppetserver/`

(maint) Clarify puppetserver log and pid locations

---

file_paths.md

Without this change, `puppet agent --configprint` will respond to and `puppet agent --genconfig` will display configurations options on Windows that aren't listed here. Add the missing configuration options to match.

(doc) Add valid Windows configurable paths

---

file_paths.md

As passenger packages will be happening for the AIO/puppet 4 release
(tickets pending), this commit adds the expected layout of the
puppetmaster package. This will need updating with the expected location
of passenger within the package.

Add puppetmaster to the specifications

---

file_paths.md

When puppet executes as root, it sets permissions for file-based
settings to either `puppet:puppet` or `root:root` depending on whether
the puppet user and group exist or not.
Previously, puppet's `logdir` setting was `/var/log/puppetlabs`. If the
puppet user didn't exist, then puppet would set permissions to
root:root with mode 0750. If you later installed `puppetserver`, it
would create its log directory in `$logdir/puppetserver`, create the
puppet user and group, start the JVM as puppet, and fail to write to
its logfile, due to permissions on the grandparent `logdir`.
This commit changes the `logdir` to `/var/log/puppetlabs/puppet`, so
that puppet can manage permissions on its `logdir` without affecting
puppetserver, or other packages.
Note mcollective.log remains where it is.

(PUP-4194) Isolate puppet's logdir

---

file_paths.md

Under the current plan, server component config files will live in
/etc/puppetlabs/<component> - there will not be a config directory
under /opt/puppetlabs/server/apps/<component>.

(packaging) Remove reference to etc/ under app dir for server layout

---

file_paths.md

- Particularly in the windows agent file section it was confusing   for many people to see what moved and what didn't

(maint) Add section separation for increased readability 

---

file_paths.md

The *nix agent package is currently laying down a VERSION file, the equivalent file for Windows is in https://github.com/puppetlabs/puppet_for_the_win/pull/117

Update puppet-agent layout with VERSION file

---

file_paths.md

PUP-4854 changed the PMT TEMP location on Windows (module_working_dir)
to use a shorter path. Update that location in the specification to
match.

(PUP-4854) Update PMT TEMP location on Windows

---

file_paths.md

Add a directory `/etc/puppetlabs/code-staging` which will be the directory
where users will lay down and interact with code if they are using the file
sync service. The File Sync service will then sync this code into the codedir.
Add the File Sync service datadir at
`/opt/puppetlabs/data/puppetserver/filesync`. This is where the File Sync
storage service and client service will keep the git directories they use for
storing data.

(PE-9922) Update file paths specification for File Sync service paths

---

file_paths.md

Adding new section with default paths of pxp-agent for Windows and *nix
platforms.

(CTH-359) Add new pxp-agent section to file_paths.md

---

file_paths.md

- It was decided that writing a JSON based pxp-module-puppet.conf
was a difficult proposition for the Windows MSI based on
that requiring a custom action.  This would have been required
on Windows since Windows has the ability to relocate the
binary installation directory.
However, given that the pathing structure under the top-level
installation directory is fixed, we can use relative paths to
assume default values for the pxp-module-puppet "interpreter"
and "puppet_bin" configuration settings.  The pxp-agent code
is being modified as such, and therefore the MSI no longer
needs to lay down a pxp-module-puppet.conf
Furthermore, on PE, a module will write the appropriate
configuration settings after initial contact with a master.

(PCP-91) MSI omits pxp-module-puppet.conf

---

file_paths.md

This commit annotates pxp-agent's log and spool directories
to indicate they are created by package installation.

(PCP-101) Annotate pxp-agent's log and spool directories

---

language/types_values_variables.md

Removes mention of descending ranges for Integer type from the
type specification.

(PUP-5658) Disallow numeric types with ranges where to < from

---

language/expressions.md
language/lexical_structure.md
language/types_values_variables.md

This adds a specification of the Type Alias Expression to
expressions.md
The lexical_structure.md is also updated (basically moving
type from being reserved to a real keyword. In the process, the list of
keywords were sorted.

(PUP-5742) Specify the Type Alias expression and type keyword

---

language/expressions.md

This contains both the missing specification PUP-6173 for multi assignments in general, and for PUP-6174 (new feature) where multiple variables can be accessed "at once" from a class reference.

(PUP-6173)(PUP-6174) Specify multi-assign from array, hash, and class

---

language/calls.md
language/expressions.md
language/types_values_variables.md

This adds a specification of the new operation:
* Ability to call a type (general information)
* Specification per type that supports new

(PUP-5966) Specify new operation

---

file_paths.md

I know at least the product should be referenced as `puppetdb` instead of `puppet-db`, but does anyone know if the conf file is `puppetdb.conf` vs `puppet-db.conf` ? @ajroetker @wkalt

(maint) Fix how puppetdb is referenced in file path doc

---

language/lexical_structure.md

Before this, the description and regular expressions used to specify the
NAME and WORD tokens were not accurate.
This improves the description:
* NAME is a subset of WORD
* hyphens may be used inside a WORD
* underscore may be used anywhere in a WORD
* :: can be used in a word, but not :

(PUP-6625) Improve description of Bare Words and Qualified References

---

language/modus-operandi.md

Before this, the specification was vague on the rules. In particular it
was missing:
* That the evaluation is recursive
* That all files are processed in alpha numerical order based on path
* That international characters outside ASCII range have undefined order

(PUP-6005) Add description of --manifest = <a directory>

---

file_paths.md

The next version of pxp-agent will add an access log that notes all
messages received. For details, see PCP-387. This commit adds the
default locations of those access logs.
This depends on https://github.com/puppetlabs/pxp-agent/pull/477 being merged.

(PCP-458) Add pcp-access.log file path

---

file_paths.md

This adds a specification for the location of translation files for use
with gettext, both on Unix and on Windows.
This PR is in part a request for comment: do these seem like the correct directories for PO files?

(PUP-6934) Update file path specification to include locale directories

---

file_paths.md

Prior to this commit, mcollective logs were placed directly in
/var/log/puppetlabs which is the only component to not have
its own directory
After this commit, mcollective logs go in a mcollective directory

(PE-10715) Move mcollective logs into their own directory

---

language/types_values_variables.md

This specifies Data and RichData. It also cleans up the specification of
Hash and Array since the spec was behind in stating that unparameterized
Array and Hash types restrict entries to Data when they are in fact
unrestricted (Any).
The types `Object` and `TypeSet` are also added to the specification as
placeholders - mostly to make the RichData specification complete. The
two experimental types (`Object`, and `TypeSet` are not yet specified).

(PUP-7481) Specify Data and RichData

---

language/func-api.md

Before this, there was no text in the specification that mentioned that
metadata.json must list another module as a dependency in order for its
functions to be found.
Now this is added last in the section about "autoloading".

(PUP-6857) Clarify the role of metadata.json for function loading

---

language/types_values_variables.md

This commit describes how a Boolean can be constrained to either `true`
or `false` using a type parameter.

(PUP-8118) Update language specification Boolean type parameter

---

language/func-api.md

Before this update, the `call_function` section of func-api.md
incorrectly reflected the 3.x style of
`call_function(func_name, args, &block)`. This patch corrects it
to reflect the 4.x style of `call_function(func_name, *args, &block)`.

(DOCUMENT-773) Correct call_function specification in func-api.md

---

README.md
models/pn.md

This commit adds a description of the model used when working with the
Puppet Extended S-Expression Notation (PN).

(PUP-8482) Add description of PN-model

---

language/templates.md

Change to EPP comment tag behavior and addition of a left trimming EPP comment tag.
Also contains some trailing space cleanup in a separate commit

(PUP-8476) left trimming for epp comments

---

moving_modules.md

Describes the user stories, file paths, and technical issues around extracting non-core types and providers from puppet.

(PUP-4380) Describe plan for moving non-core modules out of puppet

---

tasks/README.md

Powershell, bash, and scriptable languages like Ruby/Python all fit
better to different input methods. Right now you can only really use the
default if you have implementations across several of those types. Allow
specifying `input_method` for individual implementations so they can use
the type most appropriate for that executable.

Propose adding input_method to implementations

---

README.md
language/apply.md
language/lexical_structure.md

Introduces the ApplyExpression, reserving `apply` and `plan` as keywords
for future use. Expect to add PlanDefinition docs at a later date.

(BOLT-638) Updates to introduce 'apply' to the Puppet language

---

tasks/README.md

This includes a note about hardcoded file path separator needing to be '/'

(PUP-9081) Update tasks spec to specify file path separator

---

file_paths.md

There are two commits here:
- The first creates a new, separate section in file_paths.md for Puppet 6, where mcollective is removed and vendor_modules is added (these changes have already been made in the puppet-agent repo).
- The second updates the Windows paths used for Puppet 6 so that they more closely match their *nix counterparts (this work has not been done yet but will start very soon). Summary of changes:
- The structure of `C:\ProgramData` has been left alone.
- The ruby installation has moved from its own subdirectory (`sys/ruby`) to the same prefix used by other components.
- Ditto for items in `sys/tools`
- The components hiera, puppet, and pxp-agent also move from their own eponymous directories to the usual prefix.

(PA 1924) Updates to puppet-agent paths for Puppet 6

---

file_paths.md

There was incorrect spacing making it look like ruby was under
Puppet\puppet\ and not Puppet\puppet\lib for windows

(maint) Update lib/ruby to be correctly spaced for windows

---

tasks/README.md

It was left unclear whether there was a fixed relative path between
`_installdir` and the task executable. Clarify that the task executable
should be located within the `_installdir` to simplify requiring other
files and testing the task from source.

Clarify tasks and _installdir

---

language/resource-api/README.md

There were some inaccuracies vs the actual implementation and some copy
editing to make the document flow better.

(FM-7878) Update transport docs

---

language/resource-api/README.md

* Emphasise source of design constraint
* Emphasise recommendation to use these keys when applicable
* Add `password` key following feedback from the bolt team

(PUP-9747) update bolt transport key description

---

language/resource-api/README.md

The text and examples have been inconsistent with how `desc` vs `docs`
has been handled. This change fixes the text and examples to all show
and require `desc`, but accept `docs` in places where we showed it
previously.

(maint) fix desc/docs confusion

---

file_paths.md

This commit adds aditional puppet device related paths under `confdir`.
Puppet device SSL certs were moved under `deviceconfdir` to avoid certificate loss on backup/restore.
Implementation for this change: https://github.com/puppetlabs/puppet/pull/7612

(PUP-8736) Update puppet device paths

---

tasks/README.md
tasks/task.json

This adds a "default" key to the parameter specification to set a value 
that should be passed to the task if the parameter isn't provided. This 
value must satisfy the "type" of the parameter.
This should be backward-compatible so long as the task implementation is
correctly written to match the parameter type specification. Specifically, task
authors should understand that the "default" field is advisory to the task
runner and should not assume that a parameter of type `Optional` will always
have a value just because it has a "default" specified.

Allow task parameters to have default values

---

.travis.yml
tasks/README.md
tasks/error.json
tests/.gitignore
tests/Gemfile
tests/spec/spec_helper.rb
tests/spec/tasks/schema_spec.rb

Previously the error.json schema file was neither a valid JSON document or even
a valid Schema document.  This commit:
- Adds a missing comma
- Changes the schema specification from default (which is no longer allowed) to
Draft-06, the same as task.json
---
Previously there was no validation on JSON schema documents in this repository.
Now that the Forge API directly links to this file, it is important that is at
the very least a valid JSON Schema document.
This commit adds a smoke test to validate that the tasks JSON schema documents
are syntatically valid.  This commit also adds a Travis CI configuration file
so that the tests can be run automatically.
---
The Forge API no longer hosts its own copy of the Tasks Schema document and now
proxies from this repository directly [1]
This …

(maint) Update JSON Schema Documents for Tasks

---

tasks/README.md

This commit changes the language in the description of the
purpose of the `private` metadata attribute to make it clear
that this is the key's intention, not the behavior in any
particular UI (as of PE 2019.5, `private` is not supported
in the PE Console).

(maint) update language for task private attribute

---

language/expressions.md

Array - Hash removes [key, value] entries in the hash from the array, similar to how Array + Hash adds [key, value] entries like:
```
[1,2,3] + {a => 10, b => 20}    # => [1,2,3, [a, 10], [b, 20]]
```

(PUP-7930) Update Array - Hash example

---

language/resource-api/README.md

The resource_api implements `context.err` but not `context.error` as documented here.

Fix use of unknown method .error

---

language/resource-api/README.md

This PR coincides with the work for puppetlabs/puppet-resource_api#225
to add the new custom_insync feature and functionality to rsapi resources;
It covers a common use case in the code and explains the purpose and some
implementation concerns.

(GH-225) Add custom_insync to rsapi docs
